
name: Secrets SDK Publish
"on":
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        check-latest: true
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Publish
      working-directory: packages/secrets
      run: |
        sed -i "s/\"private\": true/\"private\": false/" package.json
        npx -y npm-cli-login
        npm publish --access public --tag next
        # npm dist-tag @zowe/secrets-for-zowe-sdk@$(cat package.json | jq -r .version) zowe-v2-lts
        # npm dist-tag @zowe/secrets-for-zowe-sdk@$(cat package.json | jq -r .version) next  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
        NPM_PASS: ${{ secrets.ARTIFACTORY_PASSWORD }}
        NPM_EMAIL: ${{ secrets.ZOWE_ROBOT_EMAIL }}
        NPM_REGISTRY: "https://zowe.jfrog.io/zowe/api/npm/npm-local-release"
        NPM_SCOPE: "@zowe"
