name: SonarCloud

on:
  workflow_run:
    workflows: ["Zowe CLI"]
    types: [completed]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.workflow_run.head_ref }}

    - name: Configure Sonar Scan
      uses: zowe-actions/octorelease-script@master
      env:
        COVERAGE_ARTIFACT: "zowe-cli.yml/ubuntu-latest-18.x-results:__tests__/__results__"
      with:
        script: sonarConfig

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
