name: Update GitHub project

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  update-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    steps:
    - uses: zowe-actions/shared-actions/project-move-item@actions/project-move-item
      with:
        assign-author: true
        item-status: In Progress
        project-number: 21
        project-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
